export const drones = [
    {
      id: 'HCC001',
      name: 'Drone 1',
      battery: 85,
      signalStrength: 95,
      location: {
        lat: 51.505,
        lng: 9.09,
      },
      altitude: 120,
      speed: 10,
      minDistance: 5,
    },
    {
      id: 'HCC002',
      name: 'Drone 2',
      battery: 60,
      signalStrength: 70,
      location: {
        lat: 50.505,
        lng: 9.085,
      },
      altitude: 100,
      speed: 12,
      minDistance: 6,
    },
    {
      id: 'HCC003',
      name: 'Drone 3',
      battery: 40,
      signalStrength: 50,
      location: {
        lat: 49.505,
        lng: 9.08,
      },
      altitude: 80,
      speed: 14,
      minDistance: 7,
    },
    {
      id: 'HCC004',
      name: 'Drone 4',
      battery: 20,
      signalStrength: 30,
      location: {
        lat: 48.505,
        lng: 9.075,
      },
      altitude: 60,
      speed: 16,
      minDistance: 8,
    },
    {
      id:  'HCC005',
      name: 'Drone 5',
      battery: 10,
      signalStrength: 10,
      location: {
        lat: 47.505,
        lng: 9.07,
      },
      altitude: 40,
      speed: 18,
      minDistance: 9,
    },
  ];
